# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Force Gradle + game JVM (mixin crashes on JDK 26, use 21-23)
org.gradle.java.home=C:/Users/Admin/.jdks/corretto-23.0.2


minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=1.21.4
maven_group=ru.levin
archives_base_name=duquin

# Dependencies
fabric_version=0.119.3+1.21.4